'use client';

import { useEffect, useRef, useState, useId, type ReactNode, type FormEvent } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDown, Phone, Menu, Plus, CloudRain, MoveHorizontal, Paperclip, Check, Copy, MapPin, ChevronDown } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetClose, SheetDescription } from '@/components/ui/sheet';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { business, services, stages, problems } from '@/lib/roofline-data';
import { HeroMedia, RoofMedia } from '@/components/roof-media';
import { roofingMedia } from '@/lib/roofline-media';
import { demoStartedAt, demoDurationMs } from '@/app/demo-start';

const clamp = (x:number,min=0,max=1) => Math.max(min,Math.min(max,x));
function Arrow({diagonal=true}:{diagonal?:boolean}) {return diagonal?<ArrowUpRight size={19} strokeWidth={1.5}/>:<ArrowRight size={20} strokeWidth={1.5}/>;}
function Label({children,light=false}:{children:ReactNode;light?:boolean}) {return <p className={`eyebrow ${light?'light':''}`}><span className="label-line"/>{children}</p>;}
function Button({children,href='/contact',outline=false,light=false}:{children:ReactNode;href?:string;outline?:boolean;light?:boolean}) {return <a href={href} className={`cta ${outline?'outline':''} ${light?'on-dark':''}`}><span>{children}</span><Arrow/></a>;}
function Photo({kind='hero',className='',priority=false,alt}:{kind?:'hero'|'detail'|'property';className?:string;priority?:boolean;alt?:string}) {const descriptions={hero:'Completed slate roof and brick chimneys on a British red-brick house',detail:'Slate roof texture, brick chimney and lead flashing detail',property:'Dark slate roof on a light-rendered British property'};return <img className={className} src={`/images/${kind}-1200.webp`} srcSet={`/images/${kind}-480.webp 480w, /images/${kind}-768.webp 768w, /images/${kind}-1200.webp 1200w`} sizes="(max-width: 767px) 100vw, (max-width: 1000px) 60vw, 60vw" alt={alt||descriptions[kind]} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':undefined} width="1200" height="896"/>;}


function Countdown(){
 const [remaining,setRemaining]=useState<number|null>(null);
 useEffect(()=>{const update=()=>setRemaining(Math.max(0,Date.parse(demoStartedAt)+demoDurationMs-Date.now()));update();const id=setInterval(update,1000);return()=>clearInterval(id);},[]);
 const seconds=remaining===null?null:Math.ceil(remaining/1000);
 const parts=seconds===null?['—','—','—','—']:[Math.floor(seconds/86400),Math.floor(seconds/3600)%24,Math.floor(seconds/60)%60,seconds%60].map(x=>String(x).padStart(2,'0'));
 return <aside className="demo-bar" aria-label="Seven-day website demo"><span className="demo-copy"><span className="demo-tag">WEBSITE PREVIEW</span><span>Just a demo · Available for 7 days</span></span>{remaining===0?<strong className="expired">This preview has expired.</strong>:<div className="countdown" role="timer" aria-label="Time remaining in the seven-day demo">{parts.map((v,i)=><span className="time-part" key={i}><b>{v}</b><span>{['Days','Hours','Minutes','Seconds'][i]}</span>{i<3&&<i>:</i>}</span>)}</div>}</aside>;
}
function Logo(){return <a href="/" className="wordmark" aria-label="Cotham Roofing Limited home"><svg aria-hidden="true" width="39" height="37" viewBox="0 0 42 40"><path d="M2 22 21 5l19 17M8 28 21 16l13 12M15 34h12" stroke="currentColor" strokeWidth="2" fill="none"/></svg><span>COTHAM ROOFING<small>LIMITED · ROOFING SPECIALISTS</small></span></a>;}
function Header(){
 const [scrolled,setScrolled]=useState(false);const [open,setOpen]=useState(false);
 useEffect(()=>{const update=()=>setScrolled(window.scrollY>60);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update);},[]);
 return <><Countdown/><header className={`header ${scrolled?'compact':''}`}><div className="nav-inner"><Logo/><nav className="desktop-nav" aria-label="Main navigation"><a href="/#services">Services <ChevronDown size={13}/></a><a href="/our-work">Our work</a><a href="/about">About</a><a href="/#areas">Areas we cover</a></nav><div className="nav-contact"><a className="nav-phone" href={business.tel}>{business.phone}</a><a className="nav-quote" href="/contact">Get a free quote <Arrow/></a></div><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="menu-trigger" aria-label="Open navigation"><Menu size={26}/></button></SheetTrigger><SheetContent className="mobile-menu" side="right"><SheetTitle className="menu-title">COTHAM ROOFING LIMITED</SheetTitle><SheetDescription className="sr-only">Browse roofing services, projects and contact details.</SheetDescription><nav aria-label="Mobile navigation">{[['Services','/#services'],['Our work','/our-work'],['About','/about'],['Areas we cover','/#areas'],['Contact','/contact']].map(([name,url])=><SheetClose asChild key={name}><a href={url}>{name}<Arrow/></a></SheetClose>)}</nav><a className="menu-phone" href={business.tel}>{business.phone}</a><Button>Get a free quote</Button></SheetContent></Sheet></div></header></>;
}
function Footer(){return <footer className="footer"><div className="footer-top"><div><Logo/><p>Roofing across Bristol<br/>and surrounding areas.</p></div><nav aria-label="Footer services"><span className="footer-label">YOUR ROOF</span>{services.map(s=><a key={s.slug} href={`/${s.slug}`}>{s.name}</a>)}</nav><nav aria-label="Footer navigation"><span className="footer-label">COTHAM ROOFING</span><a href="/our-work">Our work</a><a href="/about">About us</a><a href="/#areas">Areas we cover</a><a href="/contact">Get in touch</a></nav><div className="footer-contact"><span className="footer-label">LET'S TALK</span><a href={business.tel}>{business.phone}<Arrow/></a><p>Bristol, UK</p></div></div><div className="footer-brand" aria-hidden="true">COTHAM ROOFING<span>LIMITED</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Cotham Roofing Limited · Website concept</span><div><a href="/privacy">Privacy</a><a href="/legal">Legal information</a><a href="#top">Back to top ↑</a></div></div></footer>;}
function SiteFrame({children,home=false}:{children:ReactNode;home?:boolean}){
 useEffect(()=>{const nodes=document.querySelectorAll('[data-reveal]');const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)return;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target);}}),{threshold:0.1});nodes.forEach(n=>{if(n.getBoundingClientRect().top>innerHeight){n.classList.add('will-reveal');observer.observe(n);}});return()=>observer.disconnect();},[]);
 return <div id="top" className={home?'site home':'site internal'}><a className="skip-link" href="#main">Skip to content</a><Header/><main id="main">{children}</main><Footer/><div className="mobile-conversion"><a href={business.tel}><Phone size={17}/>Call</a><a href="/contact">Free quote<Arrow/></a></div></div>;
}
function Hero(){return <section className="hero"><div className="hero-image"><HeroMedia/><div className="hero-shade"/></div><div className="hero-content wrap"><Label light>ROOFING ACROSS BRISTOL & SURROUNDING AREAS</Label><h1><span>BUILT TO HANDLE</span><span>BRITISH <em>WEATHER.</em></span></h1><p className="hero-description">Roof repairs, replacements and roofline work<br className="desktop-break"/> for homes across Bristol and surrounding areas.</p><div className="hero-actions"><Button>Get a free quote</Button><Button href="/our-work" outline light>View our work</Button></div></div><div className="hero-bottom wrap"><a href="#built-properly" className="scroll-cue"><span className="scroll-icon"><ArrowDown size={18}/></span>SCROLL TO DISCOVER</a><div className="hero-location"><MapPin size={16}/>BRISTOL, UK</div><span className="image-note">Illustrative demo imagery</span></div><div className="hero-side">PROTECTION STARTS AT THE TOP.</div></section>;}
function TrustStrip(){return <section className="trust-strip"><div className="wrap trust-inner"><div className="trust-line"><span className="trust-count">7</span><div>GOOGLE REVIEWS<small>Local reputation, built over time.</small></div></div><span className="trust-divider"/><p>One roof. Many layers.<br/><b>Every detail matters.</b></p><span className="trust-divider"/><div className="trust-weather"><CloudRain strokeWidth={1} size={36}/><span>MADE FOR OUR HOMES.<br/><b>READY FOR OUR WEATHER.</b></span></div></div></section>;}

// A functional architectural cutaway diagram. Consistent geometry across all stages.
// Replace this demonstrator with the asset manifest's photographic sequence when supplied.
function RoofDiagram({progress=0,small=false}:{progress?:number;small?:boolean}){
 const id=useId().replace(/:/g,'');const p=clamp(progress,0,6);const old=clamp(1-p);const membrane=clamp((p-1)*1.6);const battens=clamp(p-2);const tiles=clamp(p-3);const finish=clamp(p-4);const zoom=1+Math.sin((p/6)*Math.PI)*.06;
 return <svg className={`roof-diagram ${small?'small':''}`} viewBox="0 0 800 560" role="img" aria-label={`Illustrated roof layers: ${stages[Math.min(6,Math.floor(p))][0]}`}>
 <defs><linearGradient id={`${id}-mem`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#171A18"/><stop offset="1" stopColor="#171A18"/></linearGradient><linearGradient id={`${id}-tile`} x1="0" y1="0" x2="0" y2="1"><stop stopColor="#A94F36"/><stop offset="1" stopColor="#A94F36"/></linearGradient><pattern id={`${id}-grid`} width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" stroke="#F2EFE7" strokeOpacity=".065" fill="none"/></pattern></defs>
 <rect width="800" height="560" fill={`url(#${id}-grid)`}/>
 <g className="diagram-roof" transform={`translate(${400-400*zoom} ${280-280*zoom}) scale(${zoom})`}>
 <g fill="none" stroke="#C6B99F" strokeWidth="1" opacity=".22"><path d="M95 470 430 535 736 365M95 475v-14M430 541v-13M736 370v-13"/><path d="m87 246 290-151 365 105M82 240l10 9M372 90l9 10M738 195l10 10"/></g>
 <g stroke="#77766F" strokeWidth="1.5"><path d="m115 319 319 105v74L115 390Z" fill="#171A18"/><path d="m434 424 276-185v76L434 498Z" fill="#171A18"/><path d="m115 319 262-166 57 271Z" fill="#171A18"/></g>
 <g fill="none" stroke="#C6B99F" strokeWidth="6">{Array.from({length:12},(_,i)=>{const t=i/11;return <path key={i} d={`M${115+319*t} ${319+105*t} L${377+333*t} ${153+86*t}`}/>;})}<path d="M115 319 434 424M377 153 710 239" strokeWidth="9"/></g>
 <path d="m115 319 262-166 333 86-276 185Z" fill={`url(#${id}-mem)`} opacity={membrane}/>
 <g fill="none" stroke="#C6B99F" strokeWidth="1" opacity={membrane*.23}>{Array.from({length:6},(_,i)=>{const t=i/6;return <path key={i} d={`M${115+262*t} ${319-166*t} L${434+276*t} ${424-185*t}`}/>;})}</g>
 <g fill="none" stroke="#C6B99F" strokeWidth="7">{Array.from({length:9},(_,i)=>{const t=(i+.45)/9;return <path key={i} opacity={clamp(battens*11-i)} d={`M${115+262*t} ${319-166*t} L${434+276*t} ${424-185*t}`}/>;})}</g>
 <g>{Array.from({length:10},(_,row)=>Array.from({length:15},(_,col)=>{const u=col/15,v=row/10;const at=(a:number,b:number)=>[115+319*a+262*b+14*a*b,319+105*a-166*b-19*a*b];const pts=[at(u,v),at((col+.98)/15,v),at((col+.98)/15,(row+.96)/10),at(u,(row+.96)/10)].map(x=>x.join(',')).join(' ');const isMissing=(row===5&&col===4)||(row===2&&col===10)||(row===7&&col===8);return <g key={`${row}-${col}`}><polygon points={pts} fill={((row+col)%4===0)?'#77766F':'#171A18'} stroke="#171A18" strokeWidth=".6" opacity={isMissing?0:clamp(old*12-(9-row))}/><polygon points={pts} fill={`url(#${id}-tile)`} stroke="#C6B99F" strokeWidth=".6" opacity={clamp(tiles*12-row-col*.06)}/></g>;}))}</g>
 <g opacity={finish} fill="none"><path d="m377 151 333 86" stroke="#A94F36" strokeWidth="12"/><path d="m115 322 319 105 276-185" stroke="#C6B99F" strokeWidth="7"/><path d="M436 429v60" stroke="#77766F" strokeWidth="5"/></g>
 <g fill="none" stroke="#C6B99F" strokeWidth="1" opacity=".7"><path d="M555 277h136l45-45"/><circle cx="555" cy="277" r="3" fill="#C6B99F"/><path d="M252 370 139 420H65"/><circle cx="252" cy="370" r="3" fill="#C6B99F"/></g>
 </g>
 <text x="600" y="214" fill="#C6B99F" fontSize="12" fontFamily="monospace">ROOF BUILD-UP</text><text x="50" y="442" fill="#C6B99F" fontSize="12" fontFamily="monospace">STRUCTURAL LAYERS</text>
 <text x="400" y="552" textAnchor="middle" fill="#C6B99F" fontSize="12" fontFamily="monospace">ARCHITECTURAL ILLUSTRATION · NOT A CONSTRUCTION SPECIFICATION</text>
 </svg>;
}
function RoofExperience(){
 const ref=useRef<HTMLElement>(null);const [progress,setProgress]=useState(0);const [reduced,setReduced]=useState(false);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const update=()=>{frame=0;if(!ref.current||media.matches)return;const rect=ref.current.getBoundingClientRect();setProgress(clamp(-rect.top/(rect.height-window.innerHeight))*6);};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);};const onPreference=()=>{setReduced(media.matches);scroll();};onPreference();window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);media.addEventListener('change',onPreference);return()=>{window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll);media.removeEventListener('change',onPreference);cancelAnimationFrame(frame);};},[]);
 const stage=Math.min(6,Math.floor(progress+.04));
 function scrub(v:number[]){const p=v[0];setProgress(p);if(!reduced&&ref.current){const sectionY=window.scrollY+ref.current.getBoundingClientRect().top;window.scrollTo({top:sectionY+(p/6)*(ref.current.offsetHeight-window.innerHeight),behavior:'instant'});}}
 return <section id="built-properly" className={`roof-sequence ${reduced?'reduced':''}`} ref={ref}><div className="roof-pin"><div className="wrap roof-intro"><Label light>01 / BUILT PROPERLY</Label><div className="section-heading"><h2>WHAT'S UNDER<br/>A GOOD <em>ROOF?</em></h2><p>A roof is more than the tiles you see. <br/>Scroll to see how the layers come together.</p></div></div><div className="wrap roof-stage-layout"><div className="roof-stage-copy"><span className="stage-counter">0{stage+1}<small>/ 07</small></span><h3>{stages[stage][0]}</h3><p>{stages[stage][1]}</p>{stage===6?<a href="/contact" className="text-link on-dark">Get a free roof quote <Arrow/></a>:<span className="roof-hint"><ArrowDown size={15}/> SCROLL TO BUILD · UP TO REVERSE</span>}</div><div className="roof-visual"><RoofMedia progress={progress}/><span className="drawing-label">COTHAM ROOFING / LAYER STUDY</span></div></div><div className="wrap roof-control"><span className="progress-caption">EXPOSED</span><Slider ref={root=>{const thumb=root?.querySelector('[role="slider"]');thumb?.setAttribute("aria-label","Roof construction progress");thumb?.setAttribute("aria-valuetext",stages[stage][0]);}} aria-label="Roof construction progress" min={0} max={6} step={.01} value={[progress]} onValueChange={scrub} className="roof-slider"/><span className="progress-caption">PROTECTED</span></div><div className="wrap stage-list" aria-label="Roof construction stages">{stages.map((s,i)=><button key={s[0]} className={i===stage?'active':''} onClick={()=>scrub([i])} aria-current={i===stage?'step':undefined}><span>0{i+1}</span>{i===6?'Complete':s[0]}</button>)}</div></div></section>;
}
function Services(){return <section id="services" className="services section-pad"><div className="wrap"><Label>02 / WHAT WE DO</Label><div className="section-heading" data-reveal><h2>ONE TEAM.<br/>YOUR WHOLE <em>ROOF.</em></h2><p>From the first slipped tile<br/>to a whole new outlook.</p></div><div className="services-editorial"><a className="service-feature" href="/roof-repairs" data-reveal><Photo kind="property"/><div className="feature-shade"/><span className="service-index">01 / ROOF REPAIRS</span><div className="service-feature-copy"><h3>A LITTLE ATTENTION.<br/>A LOT OF PROTECTION.</h3><span className="round-arrow"><Arrow/></span></div><span className="illustrative-tag">Illustrative roofing detail</span></a><div className="service-list">{services.slice(1).map(s=><a href={`/${s.slug}`} key={s.slug} data-reveal><span>{s.number}</span><div><h3>{s.name}</h3><p>{s.short}</p></div><Arrow/></a>)}<a href="/fascias-soffits-guttering" data-reveal><span>06</span><div><h3>Guttering</h3><p>A clear path for British rain.</p></div><Arrow/></a></div></div></div></section>;}
function ProblemSelector(){return <section className="problems section-pad"><div className="wrap"><Label>03 / FIND YOUR NEXT STEP</Label><div className="section-heading" data-reveal><h2>WHAT'S HAPPENING<br/><em>UP THERE?</em></h2><p>You don't need to know the answer.<br/>Just tell us what you've noticed.</p></div><Tabs defaultValue="0" className="problem-tabs" orientation="vertical"><TabsList className="problem-options" aria-label="Choose a roof problem">{problems.map((p,i)=><TabsTrigger className="problem-option" value={String(i)} key={p.name}><span>{p.name}</span><Plus size={18}/></TabsTrigger>)}</TabsList><div className="problem-panels">{problems.map((p,i)=><TabsContent value={String(i)} key={p.name} className="problem-result"><div className="problem-graphic"><RoofDiagram progress={p.stage} small/></div><div className="problem-answer"><span className="small-label">A GOOD PLACE TO START</span><h3>{p.title}</h3><p>{p.text}</p><a className="text-link" href={`/contact?problem=${encodeURIComponent(p.name)}`}>Tell us about your roof <Arrow/></a><a className="related-service" href={`/${p.service}`}>Explore {services.find(s=>s.slug===p.service)?.name.toLowerCase()} <ArrowRight size={14}/></a></div></TabsContent>)}</div></Tabs><p className="selector-note">A starting point for your enquiry, not a roof diagnosis.</p></div></section>;}
function WorkSection({archive=false}:{archive?:boolean}){
 const [filter,setFilter]=useState('all');
 const cards=[{type:'Pitched roofs',name:'The bigger picture.',image:'hero' as const,description:'Roof covering · material study',id:'01'},{type:'Roofline details',name:'It’s all in the detail.',image:'detail' as const,description:'Slate, ridge & flashing · material study',id:'02'}];
 return <section id="work" className={`work section-pad ${archive?'archive':''}`}><div className="wrap">{!archive&&<><Label>04 / SELECTED WORK</Label><div className="section-heading" data-reveal><h2>WORK THAT<br/>SPEAKS FOR <em>ITSELF.</em></h2><a className="text-link" href="/our-work">Explore our work <Arrow/></a></div></>}<div className="work-disclosure"><span>THE PROJECT JOURNAL</span><p>Real projects coming soon. The images below are illustrative roofing studies for this demo.</p></div>{archive&&<Tabs value={filter} onValueChange={setFilter}><TabsList className="work-filters" aria-label="Filter roofing studies">{['all','Pitched roofs','Roofline details'].map(x=><TabsTrigger value={x} key={x}>{x==='all'?'All studies':x}</TabsTrigger>)}</TabsList></Tabs>}<div className="work-grid">{cards.filter(c=>filter==='all'||c.type===filter).map(c=><article className={`work-item work-item-${c.id}`} key={c.id} data-reveal><div className="work-image"><Photo kind={c.image}/><span className="work-number">{c.id}</span><span className="work-image-label">ILLUSTRATIVE STUDY</span></div><div className="work-caption"><div><span className="small-label">{c.description}</span><h3>{c.name}</h3></div><a href={`/contact?problem=${encodeURIComponent(c.type)}`} aria-label={`Enquire about ${c.type.toLowerCase()}`}><Arrow/></a></div></article>)}</div></div></section>;
}
function BeforeAfter(){const [position,setPosition]=useState(50);return <section className="comparison section-pad"><div className="wrap"><div className="section-heading"><div><Label light>A CHANGE IN PERSPECTIVE</Label><h2>SEE THE <em>DIFFERENCE.</em></h2></div><p>From weathered to renewed.<br/>An illustrated roof comparison.</p></div><div className="comparison-canvas"><div className="comparison-image after">{roofingMedia.comparison.after?<img src={roofingMedia.comparison.after} alt="Roof after the work"/>:<RoofDiagram progress={6}/>}</div><div className="comparison-image before" style={{clipPath:`inset(0 ${100-position}% 0 0)`}}>{roofingMedia.comparison.before?<img src={roofingMedia.comparison.before} alt="Roof before the work"/>:<RoofDiagram progress={0}/>}</div><span className="comparison-label before-label">BEFORE</span><span className="comparison-label after-label">AFTER</span><div className="comparison-divider" style={{left:`${position}%`}}><span><MoveHorizontal size={20}/></span></div><Slider ref={root=>{root?.querySelector('[role="slider"]')?.setAttribute("aria-label","Before and after roof comparison");}} className="comparison-slider" min={0} max={100} value={[position]} onValueChange={v=>setPosition(v[0])} aria-label="Before and after roof comparison"/></div><div className="comparison-foot"><span>ILLUSTRATIVE CONCEPT · NOT A COMPLETED CLIENT PROJECT</span><span>DRAG TO EXPLORE <MoveHorizontal size={15}/></span></div></div></section>;}
function Process(){const steps=[['Tell us what’s wrong','Send details or photographs of the roof.'],['Arrange an assessment','Discuss the problem and the next step.'],['Receive your quote','Agree a clear scope of work before proceeding.'],['Get the work done','From a roof problem to a finished project.']];return <section className="process section-pad"><div className="wrap"><Label>05 / HOW IT WORKS</Label><div className="section-heading" data-reveal><h2>ROOFING WITHOUT<br/>THE <em>RUNAROUND.</em></h2><p>A clear path from<br/>first conversation to final detail.</p></div><div className="process-steps">{steps.map(([name,text],i)=><div className="process-step" key={name} data-reveal><span className="step-num">0{i+1}</span><span className="step-line"/><h3>{name}</h3><p>{text}</p></div>)}</div></div></section>;}
function Reputation(){return <section className="reputation"><div className="wrap reputation-inner"><div className="review-number" data-reveal><span>7</span><p>GOOGLE REVIEWS</p></div><div className="reputation-copy" data-reveal><Label>06 / LOCAL REPUTATION</Label><h2>BUILT LOCALLY.<br/><em>TRUSTED LOCALLY.</em></h2><p>A local business. A reputation you can look into.<br/>Cotham Roofing Limited, Bristol.</p><a href="https://www.google.com/search?q=Cotham+Roofing+Limited+Bristol+reviews" target="_blank" rel="noreferrer" className="text-link">Find reviews on Google <Arrow/></a><small>7 reviews supplied for this demo. Live count and review text to be verified.</small></div></div></section>;}
function Areas(){return <section id="areas" className="areas section-pad"><div className="wrap areas-grid"><div data-reveal><Label>07 / CLOSE TO HOME</Label><h2>ROOFING AROUND<br/><em>BRISTOL.</em></h2><p>Based in Bristol. Working with homeowners<br/>in Bristol and surrounding areas.</p><p className="area-note">Tell us your postcode to check whether your<br className="desktop-break"/> property is within the service area.</p><Button href="/contact?problem=Check%20my%20area" outline>Check your area</Button></div><div className="area-diagram" aria-label="Illustrative service area centred on Bristol"><div className="area-orbit orbit-one"/><div className="area-orbit orbit-two"/><div className="area-orbit orbit-three"/><div className="area-cross horizontal"/><div className="area-cross vertical"/><span className="area-point"><MapPin size={26} strokeWidth={1}/><strong>BRISTOL</strong><small>OUR STARTING POINT</small></span><span className="area-corner top">BRISTOL / UK</span><span className="area-corner bottom">ILLUSTRATIVE COVERAGE · ENQUIRE TO CONFIRM</span></div></div></section>;}
function Emergency(){return <section className="emergency"><div className="wrap emergency-inner"><div><Label light>URGENT ROOFING ENQUIRIES</Label><h2>ROOF PROBLEM<br/><em>CAN'T WAIT?</em></h2></div><div><p>For urgent roofing enquiries,<br/>contact Cotham Roofing Limited directly.</p><a href={business.tel} className="emergency-number">{business.phone}<Arrow/></a><a className="emergency-call" href={business.tel}><Phone size={17}/> Call now</a></div></div></section>;}

function QuoteForm(){
 const [problem,setProblem]=useState('');const [files,setFiles]=useState<File[]>([]);const [error,setError]=useState('');const [summary,setSummary]=useState('');const [copied,setCopied]=useState(false);const result=useRef<HTMLDivElement>(null);
 useEffect(()=>{const query=new URLSearchParams(window.location.search).get('problem');if(query)setProblem(query);},[]);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!problem){setError('Please choose a roof problem.');return;}const form=new FormData(e.currentTarget);setError('');setSummary(`Roofing enquiry for Cotham Roofing Limited\nName: ${form.get('name')}\nPhone: ${form.get('phone')}\nPostcode: ${form.get('postcode')}\nRoof problem: ${problem}\n${form.get('message')||''}${files.length?`\nPhotos selected: ${files.map(f=>f.name).join(', ')} (not uploaded)`:''}`);setTimeout(()=>result.current?.focus(),0);}
 async function copy(){try{await navigator.clipboard.writeText(summary);setCopied(true);}catch{setError('Copy is unavailable in this browser. Select and copy the enquiry text below.');}}
 return <form className="quote-form" onSubmit={submit}><p className="form-demo-note">Demo form: prepare an enquiry to copy. Nothing is sent or uploaded. For a real enquiry, call <a href={business.tel}>{business.phone}</a>.</p><div className="form-row"><label>Your name <span>*</span><input name="name" autoComplete="name" placeholder="Full name" required maxLength={120}/></label><label>Phone number <span>*</span><input name="phone" type="tel" autoComplete="tel" placeholder="Your contact number" required minLength={7} maxLength={30}/></label></div><div className="form-row"><label>Postcode <span>*</span><input name="postcode" autoComplete="postal-code" placeholder="e.g. BS1 1AA" required maxLength={12}/></label><div className="form-field"><label htmlFor="roof-problem">Roof problem <span>*</span></label><Select value={problem} onValueChange={setProblem}><SelectTrigger id="roof-problem" aria-required="true" className="form-select"><SelectValue placeholder="Select a problem"/></SelectTrigger><SelectContent>{[...new Set([...problems.map(p=>p.name),'Check my area','Pitched roofs','Roofline details',...services.map(s=>s.name),...(problem?[problem]:[])])].map(p=><SelectItem value={p} key={p}>{p}</SelectItem>)}</SelectContent></Select></div></div><label>Tell us a little more<textarea name="message" placeholder="What have you noticed about your roof?" rows={3} maxLength={2000}/></label><label className="file-label"><Paperclip size={18}/><span>{files.length?`${files.length} photo${files.length>1?'s':''} selected`:'Add roof photos'}<small>Optional · JPG, PNG or WebP · up to 3 × 5 MB</small></span><input type="file" name="photos" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{const selected=Array.from(e.target.files||[]);if(selected.length>3||selected.some(f=>f.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type))){setError('Choose up to 3 JPG, PNG or WebP photos, no more than 5 MB each.');setFiles([]);e.target.value='';}else{setFiles(selected);setError('');}}}/><Plus size={18}/></label>{files.length>0&&<p className="file-names">{files.map(f=>f.name).join(' · ')}</p>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-bottom"><button type="submit" className="cta"><span>Request a quote</span><Arrow/></button><span>Your roof. Your next step.</span></div>{summary&&<div className="enquiry-result" tabIndex={-1} ref={result}><h3><Check size={20}/>Your enquiry is ready to copy.</h3><p>This demo has not sent your enquiry or photos. Call Cotham Roofing Limited to discuss the next step.</p><pre>{summary}</pre><button className="text-link" type="button" onClick={copy}>{copied?'Copied':'Copy enquiry'}{copied?<Check size={17}/>:<Copy size={17}/>}</button></div>}</form>;
}
function QuoteSection({contact=false}:{contact?:boolean}){return <section id="quote" className={`quote section-pad ${contact?'contact-quote':''}`}><div className="wrap quote-grid"><div className="quote-copy"><Label>{contact?'START A CONVERSATION':'08 / A GOOD PLACE TO START'}</Label>{contact?<h2>YOUR ROOF.<br/><em>LET'S TALK.</em></h2>:<h2>LET'S TAKE A LOOK<br/>AT YOUR <em>ROOF.</em></h2>}<p>Big plans or a small concern.<br/>Tell us what you have in mind.</p><a className="quote-phone" href={business.tel}><Phone size={18}/>{business.phone}</a><span className="quote-place"><MapPin size={17}/>Bristol, UK</span></div><QuoteForm/></div></section>;}
export function HomePage(){return <SiteFrame home><Hero/><TrustStrip/><RoofExperience/><Services/><ProblemSelector/><WorkSection/><BeforeAfter/><Process/><Reputation/><Areas/><Emergency/><QuoteSection/></SiteFrame>;}

function PageHero({label,title,accent,copy}:{label:string;title:string;accent:string;copy:string}){return <section className="page-hero"><div className="page-hero-image"><Photo kind="detail" priority/><div className="hero-shade"/></div><div className="wrap"><div className="breadcrumb"><a href="/">Home</a><span>/</span><span>{label}</span></div><Label light>COTHAM ROOFING LIMITED / {label.toUpperCase()}</Label><h1>{title}<br/><em>{accent}</em></h1><p>{copy}</p><Button>Get a free quote</Button></div><span className="image-note">Illustrative demo imagery</span></section>;}
export function ServicePage({slug}:{slug:string}){const service=services.find(s=>s.slug===slug)!;const titles:Record<string,[string,string]>={'roof-repairs':['A LITTLE ATTENTION.','A LOT OF PROTECTION.'],'new-roofs':['A NEW ROOF.','A FRESH START.'],'flat-roofing':['CLEAN LINES.','COVERED PROPERLY.'],'fascias-soffits-guttering':['THE FINISHING','DETAILS MATTER.'],'emergency-roofing':['ROOF PROBLEM','CAN’T WAIT?']};return <SiteFrame><PageHero label={service.name} title={titles[slug][0]} accent={titles[slug][1]} copy={service.description}/><section className="service-intro section-pad"><div className="wrap service-intro-grid"><div><Label>{service.number} / {service.name.toUpperCase()}</Label><h2>START WITH<br/>A CLOSER <em>LOOK.</em></h2><p>{service.intro}</p>{slug==='emergency-roofing'?<Button href={business.tel}>Call {business.phone}</Button>:<Button href={`/contact?problem=${encodeURIComponent(service.name)}`} outline>Tell us about your roof</Button>}</div><div className="common-problems"><span className="small-label">WHAT HAVE YOU NOTICED?</span>{service.problems.map((p,i)=><a href={`/contact?problem=${encodeURIComponent(p)}`} key={p}><span>0{i+1}</span><h3>{p}</h3><Arrow/></a>)}</div></div></section><section className="service-visual"><Photo kind={slug==='new-roofs'?'hero':'detail'}/><div><span className="small-label">ILLUSTRATIVE MATERIAL STUDY</span><h2>{service.short}</h2></div></section><Process/><div className="service-project-pending wrap"><span className="small-label">PROJECT JOURNAL</span><h3>Genuine work. Ready to be shared.</h3><p>Verified {service.name.toLowerCase()} projects will be added here when supplied.</p><a href="/our-work" className="text-link">View the project journal<Arrow/></a></div><Areas/><QuoteSection/></SiteFrame>;}
export function WorkPage(){return <SiteFrame><PageHero label="Our work" title="THE DETAILS." accent="THE DIFFERENCE." copy="A space for real roofing projects, material details and the work behind the finish."/><WorkSection archive/><BeforeAfter/><QuoteSection/></SiteFrame>;}
export function AboutPage(){return <SiteFrame><PageHero label="About" title="ROOTED IN BRISTOL." accent="FOCUSED ON YOUR ROOF." copy="Cotham Roofing Limited. Roof repairs, replacements and roofline work for homes in Bristol and surrounding areas."/><section className="about-story section-pad"><div className="wrap about-grid"><div><Label>THE PEOPLE BEHIND THE ROOFLINE</Label><h2>A LOCAL NAME.<br/>A PRACTICAL<br/><em>CONVERSATION.</em></h2></div><div><p className="large-copy">A good place to start is a clear conversation about your home.</p><p>Whether you have spotted a leak, are thinking about a new roof or need attention at the roofline, speak to Cotham Roofing Limited about your enquiry.</p><div className="honest-placeholder"><span className="small-label">OUR STORY</span><h3>More about the team, coming soon.</h3><p>The company story, team photographs and verified qualifications will be added when provided.</p></div><Button href={business.tel} outline>Speak to us</Button></div></div></section><Reputation/><Process/><QuoteSection/></SiteFrame>;}
export function ContactPage(){return <SiteFrame><section className="contact-heading wrap"><div className="breadcrumb"><a href="/">Home</a><span>/</span><span>Contact</span></div><Label>CONTACT COTHAM ROOFING LIMITED</Label><h1>LET'S TAKE A LOOK<br/>AT YOUR <em>ROOF.</em></h1></section><QuoteSection contact/><Emergency/></SiteFrame>;}
export function LegalPage({privacy=false}:{privacy?:boolean}){return <SiteFrame><section className="legal-page wrap section-pad"><Label>WEBSITE DEMO</Label><h1>{privacy?'PRIVACY':'LEGAL INFORMATION'}</h1>{privacy?<><h2>Your information in this demo</h2><p>The quote form prepares an enquiry in your browser. Your name, phone number, postcode, message and selected photographs are not submitted, uploaded or stored by the form. Reloading or leaving the page clears this temporary form state.</p><p>The copy button copies the prepared text to your clipboard only when you select it. Telephone links open your calling app. Links to Google take you to an external service with its own privacy terms.</p><p>The seven-day countdown uses one fixed date shared by all visitors. It does not use tracking cookies or browser storage.</p><h2>Before a business launch</h2><p>A full business privacy notice, data-controller contact details and a secure enquiry delivery service must be supplied and configured before collecting customer enquiries through this website.</p></>:<><h2>A concept website for Cotham Roofing Limited</h2><p>This is a seven-day website demonstration. The name, Bristol location, telephone number and 7-review count were supplied in the project brief. This preview does not establish company registration details, credentials or guarantees.</p><p>Photography is illustrative concept imagery. Roof diagrams are explanatory illustrations, not technical construction instructions. They do not show completed Cotham Roofing Limited projects. No customer testimonials have been invented.</p><h2>Company details</h2><p>Registered company number, registered address and any applicable VAT information are awaiting verified details from the business before a public business launch.</p></>}<Button href="/">Back to home</Button></section></SiteFrame>;}
